test_name: Get the health check

stages:
  - name: Check that HTTP status code equals 200
    request:
      url: https://billing-val.screening.guardanthealth.com/actuator/health
      method: GET
      headers:
        Authorization: "Basic EFInVPRxeOVqdon8hwXl"
    response:
      status_code: 200
      json:
        status: UP
        groups: ["liveness","readiness"]
